services:
  backend:
    build: ./cofrd-connect-backend
    ports:
      - "3001:3001"
    volumes:
      - ./cofrd-connect-backend:/app
      - /app/node_modules

  frontend:
    build: ./cofrd-connect-frontend
    ports:
      - "80:80"
    depends_on:
      - backend