name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./cofrd-connect-backend
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./cofrd-connect-frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest